apiVersion: v1
kind: Service
metadata:
  name: flutter-k8s-app-service
spec:
  selector:
    app: flutter-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
